# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangotwitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfood',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
